CREATE DATABASE IF NOT EXISTS internxcel;
USE internxcel;

CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT, full_name VARCHAR(150) NOT NULL, email VARCHAR(255) UNIQUE NOT NULL, mobile VARCHAR(30), college VARCHAR(180), degree VARCHAR(80), branch VARCHAR(120), year INT, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) DEFAULT 'student', status VARCHAR(20) DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_users_status (status));
CREATE TABLE domains (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(140) UNIQUE NOT NULL, description VARCHAR(500) NOT NULL, duration INT DEFAULT 30, status VARCHAR(20) DEFAULT 'active');
CREATE TABLE internships (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, domain_id INT NOT NULL, intern_id VARCHAR(40) UNIQUE NOT NULL, start_date DATE, end_date DATE, status VARCHAR(20) DEFAULT 'active', progress INT DEFAULT 0, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (domain_id) REFERENCES domains(id));
CREATE TABLE modules (id INT PRIMARY KEY AUTO_INCREMENT, domain_id INT NOT NULL, module_number INT NOT NULL, title VARCHAR(160) NOT NULL, description VARCHAR(500), learning_objectives TEXT, estimated_duration INT DEFAULT 5, prerequisites TEXT, resources TEXT, is_locked BOOLEAN DEFAULT TRUE, FOREIGN KEY (domain_id) REFERENCES domains(id));
CREATE TABLE module_completions (id INT PRIMARY KEY AUTO_INCREMENT, internship_id INT NOT NULL, module_id INT NOT NULL, status VARCHAR(30) DEFAULT 'completed', UNIQUE KEY uq_internship_module (internship_id, module_id), FOREIGN KEY (internship_id) REFERENCES internships(id), FOREIGN KEY (module_id) REFERENCES modules(id));
CREATE TABLE tasks (id INT PRIMARY KEY AUTO_INCREMENT, module_id INT NOT NULL, title VARCHAR(180) NOT NULL, description TEXT, deadline DATE, instructions TEXT, submission_type VARCHAR(40) DEFAULT 'github_url', required_links TEXT, FOREIGN KEY (module_id) REFERENCES modules(id));
CREATE TABLE submissions (id INT PRIMARY KEY AUTO_INCREMENT, task_id INT NOT NULL, user_id INT NOT NULL, github_url VARCHAR(500), live_url VARCHAR(500), linkedin_url VARCHAR(500), file_url VARCHAR(500), text_response TEXT, status VARCHAR(30) DEFAULT 'pending_review', admin_comment TEXT, submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (task_id) REFERENCES tasks(id), FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE offer_letters (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, internship_id INT NOT NULL, offer_id VARCHAR(50) UNIQUE NOT NULL, pdf_path VARCHAR(500), generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (internship_id) REFERENCES internships(id));
CREATE TABLE certificates (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, internship_id INT NOT NULL, certificate_id VARCHAR(50) UNIQUE NOT NULL, issue_date DATE NOT NULL, pdf_path VARCHAR(500), status VARCHAR(20) DEFAULT 'valid', FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (internship_id) REFERENCES internships(id));
CREATE TABLE lor_documents (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, internship_id INT NOT NULL, document_id VARCHAR(50) UNIQUE NOT NULL, pdf_path VARCHAR(500), status VARCHAR(20) DEFAULT 'valid', generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (internship_id) REFERENCES internships(id));
CREATE TABLE notifications (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, title VARCHAR(160) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_notifications_user (user_id), FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE student_rewards (id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, badge VARCHAR(100) NOT NULL, points INT DEFAULT 0, awarded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_rewards_user (user_id), FOREIGN KEY (user_id) REFERENCES users(id));
