USE internxcel;

INSERT INTO domains (name, description, duration) VALUES
('AI & Machine Learning', 'Build intelligent systems from Python foundations to model training.', 30),
('Data Science & Data Analytics', 'Turn messy data into clear decisions through analysis and storytelling.', 30),
('Full Stack Web Development', 'Design, build, and ship web products from browser to database.', 30),
('Java Development', 'Build object-oriented applications and production-ready services.', 30),
('Python Development', 'Create automation, APIs, tools, and maintainable software.', 30),
('Cloud Computing & DevOps', 'Learn infrastructure, delivery pipelines, and observability.', 30),
('Cybersecurity', 'Learn defensive security, identity, safe testing, and response.', 30),
('UI/UX Design', 'Research, prototype, and refine digital experiences people enjoy using.', 30);

INSERT INTO modules (domain_id, module_number, title, description, learning_objectives, estimated_duration, prerequisites, resources, is_locked) VALUES
(1, 1, 'Python for AI', 'Python syntax, data structures, functions, and clean code for AI work.', 'Write readable Python; work with core data structures; build reusable functions.', 4, 'None', 'Python documentation; guided exercises', FALSE),
(1, 2, 'NumPy, Pandas & Data Preparation', 'Prepare data for analysis and modeling.', 'Load, clean, transform, and validate datasets.', 4, 'Python for AI', 'NumPy docs; Pandas docs; practice dataset', TRUE),
(1, 3, 'Machine Learning Fundamentals', 'Build and evaluate foundational models.', 'Explain the ML workflow; train a baseline model; avoid data leakage.', 5, 'NumPy, Pandas & Data Preparation', 'Scikit-learn user guide', TRUE),
(1, 4, 'Supervised & Unsupervised Learning', 'Explore classification, regression, and clustering.', 'Compare supervised and unsupervised approaches; choose suitable algorithms.', 5, 'Machine Learning Fundamentals', 'Model notebooks; algorithm references', TRUE),
(1, 5, 'Model Evaluation & AI Tools', 'Measure model quality and use modern AI tools responsibly.', 'Select metrics; interpret results; document responsible AI decisions.', 4, 'Supervised & Unsupervised Learning', 'Evaluation checklist; AI tool guide', TRUE),
(1, 6, 'Deployment & MLOps', 'Package, deploy, and monitor a model service.', 'Serve a model; track versions; describe monitoring signals.', 4, 'Model Evaluation & AI Tools', 'FastAPI docs; deployment guide', TRUE),
(1, 7, 'Final AI/ML Project', 'Ship a complete project and present your work.', 'Define a problem; build a validated solution; present evidence and limitations.', 5, 'Deployment & MLOps', 'Project brief; presentation rubric', TRUE),
(2, 1, 'Python for Data Science', 'Use Python as a foundation for analytical work.', 'Write analytical Python and structure a repeatable notebook workflow.', 4, 'None', 'Python docs; notebook guide', FALSE),
(2, 2, 'NumPy & Pandas', 'Work fluently with arrays, series, and data frames.', 'Select, transform, join, and summarize tabular data.', 4, 'Python for Data Science', 'NumPy docs; Pandas docs', TRUE),
(2, 3, 'Data Cleaning & Preprocessing', 'Make raw datasets reliable and analysis-ready.', 'Handle missing values, outliers, duplicates, and inconsistent types.', 4, 'NumPy & Pandas', 'Data quality checklist; sample datasets', TRUE),
(2, 4, 'Exploratory Data Analysis', 'Find patterns and questions inside a dataset.', 'Form hypotheses; profile variables; communicate useful findings.', 5, 'Data Cleaning & Preprocessing', 'EDA notebook examples', TRUE),
(2, 5, 'Data Visualization & Insights', 'Tell a clear story with visual evidence.', 'Choose effective charts; annotate insights; avoid misleading visuals.', 4, 'Exploratory Data Analysis', 'Visualization guide; chart examples', TRUE),
(2, 6, 'Final Data Analytics Project', 'Deliver an evidence-led analytics case study.', 'Answer a real question with clean data, visuals, and recommendations.', 5, 'Data Visualization & Insights', 'Case study rubric', TRUE),
(3, 1, 'HTML & Web Fundamentals', 'Build semantic, accessible page structure.', 'Use HTML semantics, forms, metadata, and accessible landmarks.', 3, 'None', 'MDN HTML guide', FALSE),
(3, 2, 'CSS & Responsive Design', 'Create polished layouts that work across screens.', 'Use layout systems, responsive rules, and reusable visual tokens.', 4, 'HTML & Web Fundamentals', 'MDN CSS guide; responsive checklist', TRUE),
(3, 3, 'JavaScript Fundamentals', 'Add reliable behavior with modern JavaScript.', 'Use variables, functions, arrays, objects, and asynchronous code.', 4, 'CSS & Responsive Design', 'MDN JavaScript guide', TRUE),
(3, 4, 'DOM & Browser APIs', 'Connect interface actions to browser capabilities.', 'Select elements, handle events, validate forms, and use browser storage.', 4, 'JavaScript Fundamentals', 'DOM reference; browser API exercises', TRUE),
(3, 5, 'Frontend Application Development', 'Build a maintainable interactive frontend.', 'Structure components, manage state, and handle loading/error states.', 5, 'DOM & Browser APIs', 'Frontend architecture guide', TRUE),
(3, 6, 'Backend & REST APIs', 'Design and consume a production-minded API.', 'Use HTTP, validation, authentication concepts, and clear resource routes.', 5, 'Frontend Application Development', 'FastAPI docs; API design guide', TRUE),
(3, 7, 'Database Integration', 'Persist application data safely.', 'Model relationships, query records, and handle database errors.', 4, 'Backend & REST APIs', 'SQLAlchemy docs; SQL exercises', TRUE),
(3, 8, 'Final Full Stack Project', 'Ship a complete web product.', 'Plan, build, test, document, and deploy an end-to-end application.', 6, 'Database Integration', 'Project rubric; deployment checklist', TRUE),
(4, 1, 'Java Fundamentals', 'Learn the Java language and development workflow.', 'Write Java programs; use types; compile and run applications.', 4, 'None', 'Oracle Java tutorials', FALSE),
(4, 2, 'OOP in Java', 'Model systems with object-oriented design.', 'Use classes, interfaces, inheritance, and composition appropriately.', 4, 'Java Fundamentals', 'OOP reference; design exercises', TRUE),
(4, 3, 'Collections & Exception Handling', 'Build robust programs with standard collections.', 'Choose collections; handle failures; write predictable control flow.', 4, 'OOP in Java', 'Java collections docs', TRUE),
(4, 4, 'File Handling & Java APIs', 'Work with files and standard library services.', 'Read and write files; use dates, streams, and utility APIs.', 3, 'Collections & Exception Handling', 'Java API docs', TRUE),
(4, 5, 'JDBC & MySQL', 'Connect Java applications to relational data.', 'Use JDBC safely; query MySQL; manage transactions.', 5, 'File Handling & Java APIs', 'JDBC docs; SQL exercises', TRUE),
(4, 6, 'Spring Boot & REST APIs', 'Build service APIs with Spring Boot.', 'Create controllers, services, validation, and documented endpoints.', 5, 'JDBC & MySQL', 'Spring guides', TRUE),
(4, 7, 'Final Java Project', 'Deliver a complete Java application.', 'Design, implement, test, and present a working Java solution.', 6, 'Spring Boot & REST APIs', 'Project rubric', TRUE),
(5, 1, 'Python Fundamentals', 'Build a strong foundation in Python.', 'Use syntax, collections, functions, and clean coding habits.', 4, 'None', 'Python documentation', FALSE),
(5, 2, 'Functions, Modules & Packages', 'Organize Python software for reuse.', 'Create packages, manage imports, and write reusable utilities.', 3, 'Python Fundamentals', 'Packaging guide', TRUE),
(5, 3, 'OOP in Python', 'Model maintainable software with Python objects.', 'Use classes, composition, inheritance, and protocols.', 4, 'Functions, Modules & Packages', 'Python data model docs', TRUE),
(5, 4, 'File Handling & APIs', 'Build scripts that work with files and services.', 'Parse files, call APIs, handle errors, and validate responses.', 4, 'OOP in Python', 'Requests guide; API examples', TRUE),
(5, 5, 'SQL & Database Integration', 'Persist Python application data.', 'Write SQL, model relationships, and use SQLAlchemy safely.', 5, 'File Handling & APIs', 'SQLAlchemy docs; SQL exercises', TRUE),
(5, 6, 'FastAPI / Backend Development', 'Build a validated Python backend.', 'Create routes, schemas, auth boundaries, and error handling.', 5, 'SQL & Database Integration', 'FastAPI docs', TRUE),
(5, 7, 'Final Python Project', 'Ship a complete Python application.', 'Plan, implement, test, and document a production-minded project.', 6, 'FastAPI / Backend Development', 'Project rubric', TRUE),
(6, 1, 'Cloud Computing Fundamentals', 'Understand cloud concepts and service models.', 'Explain IaaS, PaaS, SaaS, regions, and shared responsibility.', 3, 'None', 'Cloud provider fundamentals', FALSE),
(6, 2, 'Linux & Networking Basics', 'Operate confidently in a server environment.', 'Use shell tools, processes, networking commands, and permissions.', 4, 'Cloud Computing Fundamentals', 'Linux handbook; networking guide', TRUE),
(6, 3, 'AWS / Cloud Services Fundamentals', 'Use core cloud services responsibly.', 'Describe compute, storage, identity, and managed database services.', 4, 'Linux & Networking Basics', 'AWS documentation', TRUE),
(6, 4, 'Git & GitHub', 'Collaborate and ship changes with version control.', 'Use branches, pull requests, reviews, and meaningful history.', 3, 'None', 'Git documentation', TRUE),
(6, 5, 'Docker & Containers', 'Package applications consistently.', 'Write Dockerfiles, build images, and run isolated services.', 4, 'Linux & Networking Basics', 'Docker docs', TRUE),
(6, 6, 'CI/CD Fundamentals', 'Automate testing and delivery.', 'Create a pipeline, manage secrets, and inspect build results.', 4, 'Git & GitHub; Docker & Containers', 'CI provider docs', TRUE),
(6, 7, 'Final Cloud Deployment Project', 'Deploy and document a cloud-hosted application.', 'Deploy safely, monitor the service, and document rollback steps.', 6, 'CI/CD Fundamentals', 'Deployment rubric', TRUE),
(7, 1, 'Cybersecurity Fundamentals', 'Learn defensive security principles.', 'Describe threats, assets, risk, and responsible security practice.', 3, 'None', 'OWASP; NIST introductions', FALSE),
(7, 2, 'Networking & Security Basics', 'Understand secure network communication.', 'Explain protocols, segmentation, TLS, and safe network configuration.', 4, 'Cybersecurity Fundamentals', 'Networking security guide', TRUE),
(7, 3, 'Linux Security', 'Harden a Linux environment defensively.', 'Use permissions, updates, logging, and least privilege.', 4, 'Networking & Security Basics', 'Linux hardening guide', TRUE),
(7, 4, 'Authentication & Authorization', 'Design secure identity boundaries.', 'Use sessions, tokens, roles, and access-control principles.', 4, 'Cybersecurity Fundamentals', 'OWASP authentication guide', TRUE),
(7, 5, 'Web Security Fundamentals', 'Recognize and prevent common web risks.', 'Apply secure input handling, validation, and safe configuration.', 4, 'Authentication & Authorization', 'OWASP Top 10', TRUE),
(7, 6, 'Security Testing & Defensive Practices', 'Test and improve systems legally.', 'Use safe labs, dependency checks, logging, and remediation plans.', 5, 'Web Security Fundamentals', 'Defensive testing checklist', TRUE),
(7, 7, 'Final Cybersecurity Project', 'Deliver a defensive security improvement plan.', 'Assess a permitted system, document risks, and recommend mitigations.', 6, 'Security Testing & Defensive Practices', 'Security project rubric', TRUE),
(8, 1, 'Design Principles', 'Build a foundation in visual and interaction design.', 'Use hierarchy, contrast, spacing, type, and composition.', 3, 'None', 'Design principles reference', FALSE),
(8, 2, 'User Research', 'Understand users before designing solutions.', 'Plan interviews, synthesize findings, and define user needs.', 4, 'Design Principles', 'Research templates', TRUE),
(8, 3, 'Wireframing', 'Turn insights into clear interface structure.', 'Sketch flows, prioritize content, and test early ideas.', 3, 'User Research', 'Wireframe examples', TRUE),
(8, 4, 'Figma & Prototyping', 'Create interactive prototypes for critique.', 'Use components, auto layout, prototypes, and handoff notes.', 4, 'Wireframing', 'Figma learning resources', TRUE),
(8, 5, 'Responsive UI Design', 'Design interfaces that adapt gracefully.', 'Use responsive layouts, accessible states, and design tokens.', 4, 'Figma & Prototyping', 'Responsive UI checklist', TRUE),
(8, 6, 'Final UI/UX Case Study', 'Present a complete product design story.', 'Show research, decisions, iterations, prototype, and measured outcome.', 6, 'Responsive UI Design', 'Case study rubric', TRUE);

INSERT INTO tasks (module_id, title, description, instructions, submission_type, required_links)
SELECT modules.id, CONCAT('Practical task: ', modules.title), CONCAT('Apply the concepts from ', modules.title, ' in a focused project.'), 'Build the task, document your decisions, and submit your work for review.', 'github_url', 'github_url'
FROM modules;
